services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start
      - --import-realm
      - --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: dev-file
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    volumes:
      - ./opt:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
